In [4]:
import sys
from pathlib import Path

import matplotlib as mpl

In [5]:
class ImportMyModules:

    def __init__(self) -> None:
        self.cwd = Path.cwd().resolve()

    def _get_repo_root(self, folder: str) -> Path:
        return next(
            parent for parent in [self.cwd, *self.cwd.parents]
            if (parent / "lib" / "peregrin" / folder).exists()
        )

    def insert_path(self, folder: str) -> None:
        repo_root = self._get_repo_root("src")

        package_root = repo_root / "lib" / "peregrin"
        print(f"Adding {package_root} to sys.path")
        sys.path.insert(0, str(package_root))

importer = ImportMyModules()
importer.insert_path("src")
importer.insert_path("data")

Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path
Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path

In [6]:
import src.compute.stats as stats_module
# from data import b_naive, b_memory

import importlib
import src.plot.tracks.reconstruct as reconstruct_module
import src.batch.tree as batch_tree_module
import src.io.load as load_module

In [7]:
importlib.reload(batch_tree_module)

make_tree = batch_tree_module.make_tree

tree = make_tree("C:\\Users\\modri\\Desktop\\Lab\\Peregrin project\\Tree test")
# tree = make_tree("C:\\Users\\modri\\Desktop\\Lab\\Peregrin project")

# tree.show()

tree_dict = tree.get()
tree_list = tree.get(type='list')


# tree.get()

In [8]:
importlib.reload(load_module)

load_data = load_module.load_data

data = load_data(r"C:\Users\modri\Desktop\Lab\Peregrin project\Data\mem_cxcl12\#memory-cxcl12#BC39#Stablized_spots.csv", retain=['POSITION_Z'], split_filename=True, split_filename_delimiter='#', split_filename_position=2)
# data = load_data(tree_dict, split_filename=True, split_filename_delimiter='#', split_filename_position=1)
data

       track_id  time_point  x_coordinate  y_coordinate POSITION_Z   set
0         196.0         0.0    446.049935    514.718016        0.0  BC39
1          46.0         0.0    105.142437    265.404884        0.0  BC39
2         193.0         0.0     57.339646    514.234949        0.0  BC39
3         199.0         0.0    533.838219    533.021939        0.0  BC39
4         198.0         0.0    962.196674    538.272284        0.0  BC39
...         ...         ...           ...           ...        ...   ...
24317     723.0      3540.0     11.838741    321.551650        0.0  BC39
24318     727.0      3540.0     41.932501    675.383134        0.0  BC39
24319     726.0      3540.0     17.251840    588.025299        0.0  BC39
24320     725.0      3540.0     19.554030    489.110600        0.0  BC39
24321     724.0      3540.0      6.165171    332.153737        0.0  BC39

[24322 rows x 6 columns]

In [9]:
data

       track_id  time_point  x_coordinate  y_coordinate POSITION_Z   set
0         196.0         0.0    446.049935    514.718016        0.0  BC39
1          46.0         0.0    105.142437    265.404884        0.0  BC39
2         193.0         0.0     57.339646    514.234949        0.0  BC39
3         199.0         0.0    533.838219    533.021939        0.0  BC39
4         198.0         0.0    962.196674    538.272284        0.0  BC39
...         ...         ...           ...           ...        ...   ...
24317     723.0      3540.0     11.838741    321.551650        0.0  BC39
24318     727.0      3540.0     41.932501    675.383134        0.0  BC39
24319     726.0      3540.0     17.251840    588.025299        0.0  BC39
24320     725.0      3540.0     19.554030    489.110600        0.0  BC39
24321     724.0      3540.0      6.165171    332.153737        0.0  BC39

[24322 rows x 6 columns]

In [10]:
importlib.reload(stats_module)

stats = stats_module.stats

spots = stats.spots(data)
spots

,track_id,time_point,x_coordinate,y_coordinate,POSITION_Z,set,frame,distance,cum_track_length,cum_track_displacement,...,cum_speed_mean,cum_mean_straight_line_speed,cum_forward_progression_linearity,direction,directional_change,cum_sum_directional_change,cum_mean_directional_change,cum_mean_directional_change_rate,cum_direction_mean,cum_direction_var
track_uid,,,,,,,,,,,,,,,,,,,,,
0,196.0,0.0,446.049935,514.718016,0.0,BC39,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,46.0,0.0,105.142437,265.404884,0.0,BC39,0,422.344599,4.223446e+02,422.344599,...,NaN,3.519538,NaN,-2.510153,NaN,NaN,NaN,NaN,-2.510153,0.000000
0,193.0,0.0,57.339646,514.234949,0.0,BC39,0,253.380165,6.757248e+02,388.710589,...,NaN,2.159503,NaN,1.760594,115.304209,1.153042e+02,115.304209,0.640579,2.766813,0.464941
0,199.0,0.0,533.838219,533.021939,0.0,BC39,0,476.868789,1.152594e+03,89.676176,...,NaN,0.373651,NaN,0.039407,98.616773,2.139210e+02,106.960491,0.445669,1.562946,0.856285
0,198.0,0.0,962.196674,538.272284,0.0,BC39,0,428.390630,1.580984e+03,516.683907,...,NaN,1.722280,NaN,0.012256,1.555608,2.154766e+02,71.825530,0.239418,0.416118,0.725771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,723.0,3540.0,11.838741,321.551650,0.0,BC39,59,399.540816,1.219409e+07,475.239524,...,3444.657704,0.000326,9.455563e-08,2.625023,25.926157,2.900973e+06,119.303046,0.000082,-2.235701,0.996397
0,727.0,3540.0,41.932501,675.383134,0.0,BC39,59,355.108932,1.219444e+07,434.884100,...,3444.758017,0.000298,8.652027e-08,1.485949,65.264125,2.901038e+06,119.300824,0.000082,-2.242017,0.996432
0,726.0,3540.0,17.251840,588.025299,0.0,BC39,59,90.777345,1.219453e+07,435.019268,...,3444.783661,0.000298,8.654295e-08,-1.846144,169.085126,2.901207e+06,119.302871,0.000082,-2.237620,0.996394
0,725.0,3540.0,19.554030,489.110600,0.0,BC39,59,98.941487,1.219463e+07,427.263966,...,3444.811610,0.000293,8.499593e-08,-1.547526,17.109534,2.901224e+06,119.298669,0.000082,-2.230424,0.996362
0,724.0,3540.0,6.165171,332.153737,0.0,BC39,59,157.526881,1.219479e+07,476.264969,...,3444.856109,0.000326,9.473861e-08,-1.655893,6.208976,2.901231e+06,119.294019,0.000082,-2.224339,0.996328

In [11]:
importlib.reload(stats_module)

stats = stats_module.stats

tracks = stats.tracks(spots)
tracks

,set,track_id,POSITION_Z,track_length,speed_min,speed_max,speed_mean,speed_sd,speed_median,x_location,...,track_end_time,mean_straight_line_speed,forward_progression_linearity,direction_mean,direction_var,mean_directional_change,mean_directional_change_rate,track_displacement,straightness_ratio,track_points
track_uid,,,,,,,,,,,,,,,,,,,,,
0,BC39,196.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,46.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,193.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,199.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,198.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,BC39,727.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,723.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,730.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,732.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322
0,BC39,724.0,0.0,1.219479e+07,0.108514,22.093806,8.356832,4.293356,8.060981,470.788405,...,3540.0,0.000326,9.473861e-08,-2.224339,0.996328,119.294019,0.000082,476.264969,0.000039,24322

In [12]:
importlib.reload(stats_module)

stats = stats_module.stats

frames = stats.frames(spots, grouping_level=['highest', 'lowest'])
frames

,set,time_point,frame,cum_track_length_min,cum_track_length_max,cum_track_length_mean,cum_track_length_median,cum_track_length_sd,cum_track_displacement_min,cum_track_displacement_max,...,cum_mean_directional_change_min,cum_mean_directional_change_max,cum_mean_directional_change_mean,cum_mean_directional_change_median,cum_mean_directional_change_sd,instantaneous_direction_mean,instantaneous_direction_var,cum_direction_mean,cum_direction_var,grouping_level
0,BC39,0.0,0,4.223446e+02,2.088642e+05,1.014343e+05,1.007344e+05,60334.978827,21.755160,880.744114,...,71.825530,122.605559,117.241881,120.355584,6.249979,-2.573063,0.969550,-2.193840,0.135228,set
1,BC39,60.0,1,2.092277e+05,4.128062e+05,3.104611e+05,3.100120e+05,58499.399729,3.723691,881.766858,...,117.903243,121.999905,119.682723,119.297980,0.997923,2.935761,0.965679,-3.092230,0.009680,set
2,BC39,120.0,2,4.133289e+05,6.217950e+05,5.168068e+05,5.157324e+05,60655.849205,10.366510,812.897490,...,117.786037,118.751981,118.233419,118.221037,0.237845,0.096957,0.988793,-3.088165,0.001249,set
3,BC39,180.0,3,6.224137e+05,8.273509e+05,7.262763e+05,7.238304e+05,59890.979921,15.054603,884.471327,...,117.880419,118.614647,118.208699,118.201341,0.159656,0.630189,0.982644,-3.039829,0.020184,set
4,BC39,240.0,4,8.278705e+05,1.038767e+06,9.364349e+05,9.398701e+05,62518.329276,17.017419,876.440730,...,118.155981,119.012593,118.679717,118.723758,0.215030,-0.610194,0.988796,-3.054520,0.009427,set
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,BC39,3300.0,55,1.124897e+07,1.144005e+07,1.134221e+07,1.134081e+07,55175.927513,49.343666,815.368815,...,119.342656,119.421064,119.372809,119.373197,0.018239,-1.957934,0.967516,-2.253381,0.000549,set
116,BC39,3360.0,56,1.144066e+07,1.163133e+07,1.153703e+07,1.153881e+07,55433.867044,40.025211,813.864022,...,119.245272,119.353535,119.290317,119.284982,0.031013,1.638142,0.993612,-2.260861,0.000462,set
117,BC39,3420.0,57,1.163211e+07,1.182119e+07,1.172389e+07,1.171962e+07,55287.292427,21.995739,861.166198,...,119.208986,119.278192,119.242681,119.244772,0.018575,-2.469343,0.962931,-2.298777,0.000261,set
118,BC39,3480.0,58,1.182126e+07,1.201201e+07,1.191405e+07,1.191395e+07,54828.700084,7.006179,842.727346,...,119.221252,119.291300,119.256176,119.261853,0.019481,-2.738515,0.983162,-2.296828,0.000591,set
119,BC39,3540.0,59,1.201288e+07,1.219479e+07,1.210872e+07,1.211084e+07,53287.770049,7.396024,831.946200,...,119.266395,119.308201,119.287503,119.287722,0.008660,-1.271215,0.974820,-2.314096,0.000826,set

In [13]:
spots

,track_id,time_point,x_coordinate,y_coordinate,POSITION_Z,set,frame,distance,cum_track_length,cum_track_displacement,...,cum_speed_mean,cum_mean_straight_line_speed,cum_forward_progression_linearity,direction,directional_change,cum_sum_directional_change,cum_mean_directional_change,cum_mean_directional_change_rate,cum_direction_mean,cum_direction_var
track_uid,,,,,,,,,,,,,,,,,,,,,
0,196.0,0.0,446.049935,514.718016,0.0,BC39,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,46.0,0.0,105.142437,265.404884,0.0,BC39,0,422.344599,4.223446e+02,422.344599,...,NaN,3.519538,NaN,-2.510153,NaN,NaN,NaN,NaN,-2.510153,0.000000
0,193.0,0.0,57.339646,514.234949,0.0,BC39,0,253.380165,6.757248e+02,388.710589,...,NaN,2.159503,NaN,1.760594,115.304209,1.153042e+02,115.304209,0.640579,2.766813,0.464941
0,199.0,0.0,533.838219,533.021939,0.0,BC39,0,476.868789,1.152594e+03,89.676176,...,NaN,0.373651,NaN,0.039407,98.616773,2.139210e+02,106.960491,0.445669,1.562946,0.856285
0,198.0,0.0,962.196674,538.272284,0.0,BC39,0,428.390630,1.580984e+03,516.683907,...,NaN,1.722280,NaN,0.012256,1.555608,2.154766e+02,71.825530,0.239418,0.416118,0.725771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,723.0,3540.0,11.838741,321.551650,0.0,BC39,59,399.540816,1.219409e+07,475.239524,...,3444.657704,0.000326,9.455563e-08,2.625023,25.926157,2.900973e+06,119.303046,0.000082,-2.235701,0.996397
0,727.0,3540.0,41.932501,675.383134,0.0,BC39,59,355.108932,1.219444e+07,434.884100,...,3444.758017,0.000298,8.652027e-08,1.485949,65.264125,2.901038e+06,119.300824,0.000082,-2.242017,0.996432
0,726.0,3540.0,17.251840,588.025299,0.0,BC39,59,90.777345,1.219453e+07,435.019268,...,3444.783661,0.000298,8.654295e-08,-1.846144,169.085126,2.901207e+06,119.302871,0.000082,-2.237620,0.996394
0,725.0,3540.0,19.554030,489.110600,0.0,BC39,59,98.941487,1.219463e+07,427.263966,...,3444.811610,0.000293,8.499593e-08,-1.547526,17.109534,2.901224e+06,119.298669,0.000082,-2.230424,0.996362
0,724.0,3540.0,6.165171,332.153737,0.0,BC39,59,157.526881,1.219479e+07,476.264969,...,3444.856109,0.000326,9.473861e-08,-1.655893,6.208976,2.901231e+06,119.294019,0.000082,-2.224339,0.996328

In [ ]:
importlib.reload(stats_module)

stats = stats_module.stats

tlags = stats.time_intervals(spots, grouping_level=['highest', 'lowest'])

display(tlags)

In [ ]:
importlib.reload(load_module)

load_data = load_module.load_data

data = load_data(tree_list, retain=['POSITION_Z'])
data

spots = stats.spots(data)
spots

,track_id,time_point,x_coordinate,y_coordinate,POSITION_Z,set,subset,group,frame,distance,...,cum_speed_mean,cum_mean_straight_line_speed,cum_forward_progression_linearity,direction,directional_change,cum_sum_directional_change,cum_mean_directional_change,cum_mean_directional_change_rate,cum_direction_mean,cum_direction_var
track_uid,,,,,,,,,,,,,,,,,,,,,
0,163.0,0.0,359.146286,213.254098,0.0,1,1,#memory-ctr#BC39#Stablized_spots.csv,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,62.0,0.0,249.731203,868.255973,0.0,1,1,#memory-ctr#BC39#Stablized_spots.csv,0,664.077643,...,NaN,5.533980,NaN,1.736314,NaN,NaN,NaN,NaN,1.736314,0.000000
0,61.0,0.0,780.128167,742.540054,0.0,1,1,#memory-ctr#BC39#Stablized_spots.csv,0,545.092132,...,NaN,3.757172,NaN,-0.232728,112.817745,1.128177e+02,112.817745,0.626765,0.751793,0.446737
0,335.0,0.0,818.683978,598.562539,0.0,1,1,#memory-ctr#BC39#Stablized_spots.csv,0,149.050580,...,NaN,2.498741,NaN,-1.309145,61.674175,1.744919e+02,87.245960,0.363525,-0.194575,0.637508
0,346.0,0.0,766.602304,630.277660,0.0,1,1,#memory-ctr#BC39#Stablized_spots.csv,0,60.978272,...,NaN,1.943448,NaN,2.594618,136.330830,3.108228e+02,103.607584,0.345359,0.968869,0.906023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,207.0,3540.0,887.549547,653.577613,0.0,3,2,#naive-mu#BC43#Stablized_spots.csv,59,575.004396,...,1539.720654,0.000033,2.118252e-08,-0.124230,55.744093,1.208201e+06,121.135093,0.000202,3.022650,0.995946
31,206.0,3540.0,1122.513345,99.981158,0.0,3,2,#naive-mu#BC43#Stablized_spots.csv,59,601.395894,...,1539.890540,0.000973,6.316901e-07,-1.169407,59.884274,1.208261e+06,121.128953,0.000202,3.044369,0.995995
31,0.0,3540.0,898.248052,636.855243,0.0,3,2,#naive-mu#BC43#Stablized_spots.csv,59,581.832196,...,1540.054899,0.000001,8.797343e-10,1.966488,179.673575,1.208441e+06,121.134821,0.000202,3.022580,0.995947
31,56.0,3540.0,6.651352,844.017689,0.0,3,2,#naive-mu#BC43#Stablized_spots.csv,59,915.347450,...,1540.313472,0.001529,9.928088e-07,2.913294,54.247950,1.208495e+06,121.128117,0.000202,3.019947,0.995848
31,143.0,3540.0,617.215177,456.162290,0.0,3,2,#naive-mu#BC43#Stablized_spots.csv,59,723.339474,...,1540.517805,0.000559,3.629912e-07,-0.565930,160.655174,1.208656e+06,121.132078,0.000202,3.030553,0.995939

In [ ]:
spots = stats.spots(b_naive.ctr)
tracks = stats.tracks(spots)

NameError: name 'b_naive' is not defined

In [ ]:
spots

In [ ]:

# # reconstruct(spots, color="black")

# importlib.reload(reconstruct_module)

# reconstruct = reconstruct_module.reconstruct

# print('run 1')
# reconstruct(spots, common_start=True, color='black', show_heads=True, ignore_categories=True)

# print('run 2')
# reconstruct(spots, common_start=True, color_by='distance', show_heads=True, ignore_categories=True)

# print('run 3')
# reconstruct(spots, common_start=False, color_by='distance', show_heads=True, ignore_categories=True)

# print('run 4')
# reconstruct(spots, common_start=False, color='random', show_heads=True, ignore_categories=True)

In [ ]:
%matplotlib widget

importlib.reload(reconstruct_module)
reconstruct = reconstruct_module.reconstruct
result = reconstruct(spots, color='random', align_at_start=True)

In [ ]:
%matplotlib widget

mpl.rcParams['animation.embed_limit'] = 50


anim = result.animate(speed=2.0, interval=20, controls=True, mode="jshtml")
anim

# result.figure.show()