In [1]:
import sys
from pathlib import Path

class ImportMyModules:

    def __init__(self) -> None:
        self.cwd = Path.cwd().resolve()

    def _get_repo_root(self, folder: str) -> Path:
        return next(
            parent for parent in [self.cwd, *self.cwd.parents]
            if (parent / "lib" / "peregrin" / folder).exists()
        )

    def insert_path(self, folder: str) -> None:
        repo_root = self._get_repo_root("src")

        package_root = repo_root / "lib" / "peregrin"
        print(f"Adding {package_root} to sys.path")
        sys.path.insert(0, str(package_root))

importer = ImportMyModules()
importer.insert_path("src")
importer.insert_path("data")

from importlib import reload

Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path
Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path

In [2]:
import src.data_handler.data_loader as load_module
reload(load_module)
load_data = load_module.load_data

In [3]:
# data = load_data(r"./dummy_data/testing_0")

data = load_data(
    r"./dummy_data/tree",
    colnames = {
        'id': 'track_id',
        't': 'time_point',
        'x': 'x_coordinate',
        'y': 'y_coordinate'
    },
)

C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin\src\data_handler\df_metadata_manager.py:176: InputWarning: No time units found in input files.
 Please specify the time units using <load_data result>.metadata.write(time_unit="<unit>")
  self._check()
C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin\src\data_handler\df_metadata_manager.py:176: InputWarning: No spatial units found in input files.
 Please specify the spatial units using <load_data result>.metadata.write(spatial_unit="<unit>")
  self._check()

In [4]:
data.metadata.write(spatialunits='um', timeunits='s')
data.metadata.get()

{'timeunits': 's',
 'spatialunits': 'μm',
 'nframes': 97,
 'timeinterval': 1.0,
 'columns': ['track_id',
  'time_point',
  'x_coordinate',
  'y_coordinate',
  'track_uid']}

In [5]:
data

shape: (4_656, 9)
┌──────────┬────────────┬────────────┬────────────┬───┬──────────┬─────────┬──────────┬────────────┐
│ track_id ┆ time_point ┆ x_coordina ┆ y_coordina ┆ … ┆ subset   ┆ group   ┆ subgroup ┆ subsubgrou │
│ ---      ┆ ---        ┆ te         ┆ te         ┆   ┆ ---      ┆ ---     ┆ ---      ┆ p          │
│ f64      ┆ f64        ┆ ---        ┆ ---        ┆   ┆ str      ┆ str     ┆ str      ┆ ---        │
│          ┆            ┆ f64        ┆ f64        ┆   ┆          ┆         ┆          ┆ str        │
╞══════════╪════════════╪════════════╪════════════╪═══╪══════════╪═════════╪══════════╪════════════╡
│ 1.0      ┆ 3.0        ┆ 398.279126 ┆ 240.018418 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 4.0        ┆ 403.759745 ┆ 246.280817 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 5.0        ┆ 410.293969 ┆ 252.025005 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 6.0        ┆ 417.515554 ┆ 255.846523 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 1.0      ┆ 7.0        ┆ 425.567799 ┆ 261.606225 ┆ … ┆ subset_1 ┆ ctrl    ┆ rep1     ┆ dummy_cell │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ _tracks_0. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ …        ┆ …          ┆ …          ┆ …          ┆ … ┆ …        ┆ …       ┆ …        ┆ …          │
│ 48.0     ┆ 95.0       ┆ -263.10974 ┆ 558.308107 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 7          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 96.0       ┆ -263.49867 ┆ 563.497103 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 3          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 97.0       ┆ -261.75510 ┆ 566.663271 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 1          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 98.0       ┆ -260.39627 ┆ 571.391335 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 5          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
│ 48.0     ┆ 99.0       ┆ -257.26308 ┆ 576.229309 ┆ … ┆ subset_2 ┆ treated ┆ rep2     ┆ dummy_cell │
│          ┆            ┆ 5          ┆            ┆   ┆          ┆         ┆          ┆ _tracks_2. │
│          ┆            ┆            ┆            ┆   ┆          ┆         ┆          ┆ csv        │
└──────────┴────────────┴────────────┴────────────┴───┴──────────┴─────────┴──────────┴────────────┘

In [6]:
import src.object_interface as object_module
reload(object_module)
create_object = object_module.create_object

In [7]:
data_object = create_object(data)

In [8]:
spots_df = data_object.compute_spots(data, enriched=True)
print(len(spots_df['track_uid'].unique()), " unique tracks")
spots_df

48  unique tracks

shape: (4_656, 27)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ track_id ┆ time_poin ┆ x_coordin ┆ y_coordin ┆ … ┆ cum_mean_ ┆ cum_mean_ ┆ cum_direc ┆ cum_direc │
│ ---      ┆ t         ┆ ate       ┆ ate       ┆   ┆ direction ┆ direction ┆ tion_mean ┆ tion_var  │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_change ┆ al_change ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ _ra…      ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0      ┆ 3.0       ┆ 398.27912 ┆ 240.01841 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 6         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 4.0       ┆ 403.75974 ┆ 246.28081 ┆ … ┆ null      ┆ null      ┆ 0.851874  ┆ null      │
│          ┆           ┆ 5         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 5.0       ┆ 410.29396 ┆ 252.02500 ┆ … ┆ 7.490328  ┆ 2.496776  ┆ 0.786509  ┆ 0.002136  │
│          ┆           ┆ 9         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 6.0       ┆ 417.51555 ┆ 255.84652 ┆ … ┆ 10.46095  ┆ 2.615237  ┆ 0.68677   ┆ 0.011378  │
│          ┆           ┆ 4         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 7.0       ┆ 425.56779 ┆ 261.60622 ┆ … ┆ 9.536941  ┆ 1.907388  ┆ 0.670169  ┆ 0.008939  │
│          ┆           ┆ 9         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 48.0     ┆ 95.0      ┆ -263.1097 ┆ 558.30810 ┆ … ┆ 12.019773 ┆ 0.129245  ┆ 2.751283  ┆ 0.256409  │
│          ┆           ┆ 47        ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 96.0      ┆ -263.4986 ┆ 563.49710 ┆ … ┆ 12.063364 ┆ 0.128334  ┆ 2.738304  ┆ 0.259519  │
│          ┆           ┆ 73        ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 97.0      ┆ -261.7551 ┆ 566.66327 ┆ … ┆ 12.28986  ┆ 0.129367  ┆ 2.723836  ┆ 0.268383  │
│          ┆           ┆ 01        ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 98.0      ┆ -260.3962 ┆ 571.39133 ┆ … ┆ 12.295357 ┆ 0.128077  ┆ 2.709462  ┆ 0.274562  │
│          ┆           ┆ 75        ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 99.0      ┆ -257.2630 ┆ 576.22930 ┆ … ┆ 12.343761 ┆ 0.127255  ┆ 2.695071  ┆ 0.283525  │
│          ┆           ┆ 85        ┆ 9         ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
import src.data_compute.data_frames as frames_module
reload(frames_module)
calcs = frames_module.calc

In [10]:
calcs._enrich_spots(spots_df, t_step= 1.0)

shape: (4_656, 27)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ track_id ┆ time_poin ┆ x_coordin ┆ y_coordin ┆ … ┆ cum_mean_ ┆ cum_mean_ ┆ cum_direc ┆ cum_direc │
│ ---      ┆ t         ┆ ate       ┆ ate       ┆   ┆ direction ┆ direction ┆ tion_mean ┆ tion_var  │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_change ┆ al_change ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ _ra…      ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0      ┆ 3.0       ┆ 398.27912 ┆ 240.01841 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 6         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 4.0       ┆ 403.75974 ┆ 246.28081 ┆ … ┆ null      ┆ null      ┆ 0.851874  ┆ null      │
│          ┆           ┆ 5         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 5.0       ┆ 410.29396 ┆ 252.02500 ┆ … ┆ 7.490328  ┆ 2.496776  ┆ 0.786509  ┆ 0.002136  │
│          ┆           ┆ 9         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 6.0       ┆ 417.51555 ┆ 255.84652 ┆ … ┆ 10.46095  ┆ 2.615237  ┆ 0.68677   ┆ 0.011378  │
│          ┆           ┆ 4         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 1.0      ┆ 7.0       ┆ 425.56779 ┆ 261.60622 ┆ … ┆ 9.536941  ┆ 1.907388  ┆ 0.670169  ┆ 0.008939  │
│          ┆           ┆ 9         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 48.0     ┆ 95.0      ┆ -263.1097 ┆ 558.30810 ┆ … ┆ 12.019773 ┆ 0.129245  ┆ 2.751283  ┆ 0.256409  │
│          ┆           ┆ 47        ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 96.0      ┆ -263.4986 ┆ 563.49710 ┆ … ┆ 12.063364 ┆ 0.128334  ┆ 2.738304  ┆ 0.259519  │
│          ┆           ┆ 73        ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 97.0      ┆ -261.7551 ┆ 566.66327 ┆ … ┆ 12.28986  ┆ 0.129367  ┆ 2.723836  ┆ 0.268383  │
│          ┆           ┆ 01        ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 98.0      ┆ -260.3962 ┆ 571.39133 ┆ … ┆ 12.295357 ┆ 0.128077  ┆ 2.709462  ┆ 0.274562  │
│          ┆           ┆ 75        ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 48.0     ┆ 99.0      ┆ -257.2630 ┆ 576.22930 ┆ … ┆ 12.343761 ┆ 0.127255  ┆ 2.695071  ┆ 0.283525  │
│          ┆           ┆ 85        ┆ 9         ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
tracks = data_object.compute_tracks()
tracks

shape: (48, 28)
┌────────────┬──────────┬─────────┬──────────┬───┬──────────┬────────────┬────────────┬────────────┐
│ subsubgrou ┆ subgroup ┆ group   ┆ subset   ┆ … ┆ speed_sd ┆ speed_medi ┆ directiona ┆ straightne │
│ p          ┆ ---      ┆ ---     ┆ ---      ┆   ┆ ---      ┆ an         ┆ lity       ┆ ss         │
│ ---        ┆ str      ┆ str     ┆ str      ┆   ┆ f64      ┆ ---        ┆ ---        ┆ ---        │
│ str        ┆          ┆         ┆          ┆   ┆          ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪══════════╪═════════╪══════════╪═══╪══════════╪════════════╪════════════╪════════════╡
│ dummy_cell ┆ rep1     ┆ ctrl    ┆ subset_1 ┆ … ┆ 1.434158 ┆ 7.24023    ┆ 0.930173   ┆ 0.930173   │
│ _tracks_0. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep1     ┆ ctrl    ┆ subset_1 ┆ … ┆ 0.79065  ┆ 3.486127   ┆ 0.209477   ┆ 0.421677   │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep1     ┆ ctrl    ┆ subset_1 ┆ … ┆ 0.648953 ┆ 2.057925   ┆ 0.201353   ┆ 0.481521   │
│ _tracks_2. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep2     ┆ ctrl    ┆ subset_1 ┆ … ┆ 0.858003 ┆ 3.090928   ┆ 0.764987   ┆ 0.775168   │
│ _tracks_0. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep2     ┆ ctrl    ┆ subset_1 ┆ … ┆ 0.639068 ┆ 2.737676   ┆ 0.630184   ┆ 0.673595   │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ …          ┆ …        ┆ …       ┆ …        ┆ … ┆ …        ┆ …          ┆ …          ┆ …          │
│ dummy_cell ┆ rep1     ┆ treated ┆ subset_2 ┆ … ┆ 1.40604  ┆ 6.237907   ┆ 0.299199   ┆ 0.299199   │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep1     ┆ treated ┆ subset_2 ┆ … ┆ 1.090322 ┆ 5.047387   ┆ 0.171391   ┆ 0.423011   │
│ _tracks_2. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep2     ┆ treated ┆ subset_2 ┆ … ┆ 1.238897 ┆ 5.737695   ┆ 0.414093   ┆ 0.522809   │
│ _tracks_0. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep2     ┆ treated ┆ subset_2 ┆ … ┆ 0.731998 ┆ 2.74256    ┆ 0.703973   ┆ 0.741818   │
│ _tracks_1. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ dummy_cell ┆ rep2     ┆ treated ┆ subset_2 ┆ … ┆ 1.078989 ┆ 4.782083   ┆ 0.725988   ┆ 0.754523   │
│ _tracks_2. ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
│ csv        ┆          ┆         ┆          ┆   ┆          ┆            ┆            ┆            │
└────────────┴──────────┴─────────┴──────────┴───┴──────────┴────────────┴────────────┴────────────┘

In [12]:
# data_object.plot_tracks(fmt='html', smoothing_window=5, color='random', show_ids=True)

In [13]:
# data_object.plot_tracks(color='random', align_start=True, show_ids=True)

In [14]:
timepoints = data_object.compute_timepoints(inferative_error=True)

timepoints.to_pandas()

,set,time_point,frame,cum_track_length_min,cum_track_length_max,cum_track_length_mean,cum_track_length_median,cum_track_length_sd,cum_track_length_sem,cum_track_displacement_min,...,cum_mean_directional_change_mean,cum_mean_directional_change_median,cum_mean_directional_change_sd,cum_mean_directional_change_sem,tracks_contributing,instantaneous_direction_mean,instantaneous_direction_var,cum_direction_mean,cum_direction_var,grouping_level
0,set_A,3.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,set
1,set_A,4.0,1,1.225617,8.321949,4.075348,3.599075,2.109026,0.430503,1.225617,...,NaN,NaN,NaN,NaN,24,1.045694,0.974031,1.045694,0.974031,set
2,set_A,5.0,2,3.430117,17.022051,7.947141,6.401511,3.932200,0.802657,2.733488,...,24.769684,20.714868,21.834038,4.456854,24,0.476767,0.931170,0.491814,0.952129,set
3,set_A,6.0,3,5.907003,26.575393,11.827633,9.455840,5.669264,1.157234,5.287296,...,26.151808,25.019599,16.079762,3.282268,24,-0.585223,0.897527,0.021417,0.932740,set
4,set_A,7.0,4,6.942866,35.092584,15.871724,12.646872,7.775663,1.587200,6.871206,...,27.888846,30.234282,15.478031,3.159440,24,-0.379351,0.833094,-0.238734,0.902538,set
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,set_B,95.0,92,221.964326,697.052768,466.446714,492.331115,150.775737,30.776968,37.394164,...,25.821838,28.397869,8.947691,1.826440,24,-0.745782,0.905881,1.225007,0.884226,set
190,set_B,96.0,93,225.233942,704.297998,471.739020,497.759230,152.203840,31.068479,40.903911,...,25.881256,28.390069,8.944828,1.825855,24,-0.041410,0.788047,1.189188,0.881267,set
191,set_B,97.0,94,227.383648,711.318623,477.128684,502.661364,153.717050,31.377361,45.157051,...,25.934048,28.340901,8.930600,1.822951,24,-0.277838,0.873579,1.153066,0.881359,set
192,set_B,98.0,95,229.045166,719.847246,482.228011,507.342086,155.486686,31.738587,48.400029,...,25.899463,28.209882,8.924881,1.821784,24,0.424122,0.819173,1.106189,0.876709,set
193,set_B,99.0,96,232.487916,728.738419,487.432345,512.611443,157.249537,32.098427,49.351024,...,25.942314,28.281401,9.012825,1.839735,24,0.047136,0.890222,1.060549,0.874203,set

In [15]:
timepoints = data_object.compute_timepoints(grouping_level='lowest')

timepoints.to_pandas()

,subgroup,group,subset,set,time_point,frame,cum_track_length_min,cum_track_length_max,cum_track_length_mean,cum_track_length_median,...,cum_mean_directional_change_max,cum_mean_directional_change_mean,cum_mean_directional_change_median,cum_mean_directional_change_sd,tracks_contributing,instantaneous_direction_mean,instantaneous_direction_var,cum_direction_mean,cum_direction_var,grouping_level
0,rep1,ctrl,subset_1,set_A,3.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,subgroup
1,rep1,ctrl,subset_1,set_A,4.0,1,1.629535,8.321949,4.271931,2.864308,...,NaN,NaN,NaN,NaN,3,1.672949,0.491258,1.672949,0.491258,subgroup
2,rep1,ctrl,subset_1,set_A,5.0,2,3.889163,17.022051,8.736303,5.297696,...,59.055369,26.953895,14.315988,28.009389,3,1.373383,0.218348,1.554696,0.348164,subgroup
3,rep1,ctrl,subset_1,set_A,6.0,3,5.907003,25.192442,13.413622,9.141421,...,59.064454,26.764023,10.766666,27.973411,3,1.207037,0.605811,1.486660,0.440830,subgroup
4,rep1,ctrl,subset_1,set_A,7.0,4,6.942866,35.092584,18.048424,12.109822,...,48.385791,21.862702,9.536941,22.988723,3,1.376743,0.422709,1.458871,0.435182,subgroup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,rep2,treated,subset_2,set_B,95.0,92,255.825351,524.717422,401.819784,424.916581,...,28.304130,19.792723,19.054265,8.167256,3,2.065524,0.824681,2.126743,0.714301,subgroup
1548,rep2,treated,subset_2,set_B,96.0,93,259.541975,531.179931,406.947346,430.120132,...,28.118605,19.851423,19.372300,8.038337,3,-0.311877,0.782736,2.112774,0.709860,subgroup
1549,rep2,treated,subset_2,set_B,97.0,94,263.265266,535.844811,410.948239,433.734639,...,28.075232,19.986958,19.595783,7.899953,3,0.667923,0.730498,2.095292,0.703573,subgroup
1550,rep2,treated,subset_2,set_B,98.0,95,266.812055,541.909709,415.791951,438.654091,...,27.886640,19.897019,19.509060,7.802878,3,0.415659,0.791605,2.082079,0.697920,subgroup
1551,rep2,treated,subset_2,set_B,99.0,96,268.185440,545.597949,419.400469,444.418019,...,27.987280,19.901419,19.373215,7.835125,3,-0.613085,0.772972,2.085945,0.694733,subgroup

In [16]:
data_object

In [17]:
timelagstab = data_object.compute_timelags(grouping_level=["subset", "set"], bootstrap_ci=True)

timelagstab.to_pandas()

,subset,set,frame_lag,time_lag,MSD,MSD_min,MSD_max,MSD_sd,tracks_contributing,position_pairs_contributing,MSD_ci95_low,MSD_ci95_high,directional_change_mean,directional_change_var,grouping_level
0,subset_1,set_A,1,1.0,17.973682,0.008664,101.667321,17.239372,12,1152,17.098588,19.045614,-0.011809,0.125651,subset
1,subset_2,set_A,1,1.0,22.716141,0.828084,134.117884,24.346068,12,1152,21.320473,24.129238,-0.008503,0.124927,subset
2,subset_1,set_B,1,1.0,37.577134,1.798014,143.197483,23.464611,12,1152,36.305139,39.033569,0.002833,0.168827,subset
3,subset_2,set_B,1,1.0,21.855419,0.816109,93.878506,16.773945,12,1152,20.923057,22.815981,0.009982,0.120594,subset
4,subset_1,set_A,2,2.0,66.969576,3.630542,364.995566,61.009778,12,1140,63.874358,70.876943,-0.022942,0.211950,subset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,None,set_B,94,94.0,59886.222653,2039.159229,271477.825937,78198.077482,24,72,43493.991982,78759.467497,0.276659,0.792359,set
572,None,set_A,95,95.0,72434.444665,176.229885,402127.703178,106863.835353,24,48,49182.080007,110579.607225,-0.058568,0.787953,set
573,None,set_B,95,95.0,60858.524637,2342.562804,272714.637081,79580.226522,24,48,43092.239504,88249.046390,0.552895,0.668445,set
574,None,set_A,96,96.0,73602.056813,86.225042,404464.354655,109842.801830,24,24,41942.494322,137489.635059,NaN,NaN,set
575,None,set_B,96,96.0,61654.269106,2435.523589,273289.880940,81452.755102,24,24,37536.511015,105081.970480,NaN,NaN,set