In [18]:
import sys
from pathlib import Path

class ImportMyModules:

    def __init__(self) -> None:
        self.cwd = Path.cwd().resolve()

    def _get_repo_root(self, folder: str) -> Path:
        return next(
            parent for parent in [self.cwd, *self.cwd.parents]
            if (parent / "lib" / "peregrin" / folder).exists()
        )

    def insert_path(self, folder: str) -> None:
        repo_root = self._get_repo_root("src")

        package_root = repo_root / "lib" / "peregrin"
        print(f"Adding {package_root} to sys.path")
        sys.path.insert(0, str(package_root))

importer = ImportMyModules()
importer.insert_path("src")
importer.insert_path("data")

from importlib import reload

Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path
Adding C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin to sys.path

In [19]:
import src.data_handler.data_loader as load_module
reload(load_module)
load_data = load_module.load_data

In [20]:
# data = load_data(r"./dummy_data/testing_0")

data = load_data(
    r"..\..\..\cell-tracking-data\01",
    # colnames = {
    #     'id': 'track_id',
    #     't': 'time_point',
    #     'x': 'x_coordinate',
    #     'y': 'y_coordinate'
    # },
)

C:\Users\modri\Desktop\Repositories\peregrin\lib\peregrin\src\data_handler\df_metadata_manager.py:176: InputWarning: Inconsistent number of frames across input files -> found {59, 60}.
  self._check()

In [21]:
data.metadata.write(spatialunits='um', timeunits='s')
data.metadata.get()

{'timeunits': 's',
 'spatialunits': 'μm',
 'nframes': '',
 'timeinterval': 60.0,
 'columns': ['LABEL',
  'ID',
  'TRACK_ID',
  'QUALITY',
  'POSITION_X',
  'POSITION_Y',
  'POSITION_Z',
  'POSITION_T',
  'FRAME',
  'RADIUS',
  'VISIBILITY',
  'MANUAL_SPOT_COLOR',
  'MEAN_INTENSITY_CH1',
  'MEDIAN_INTENSITY_CH1',
  'MIN_INTENSITY_CH1',
  'MAX_INTENSITY_CH1',
  'TOTAL_INTENSITY_CH1',
  'STD_INTENSITY_CH1',
  'CONTRAST_CH1',
  'SNR_CH1']}

In [22]:
data

shape: (277_766, 7)
┌──────────┬────────────┬──────────────┬──────────────┬──────────┬────────┬─────────────────────┐
│ track_id ┆ time_point ┆ x_coordinate ┆ y_coordinate ┆ set      ┆ subset ┆ group               │
│ ---      ┆ ---        ┆ ---          ┆ ---          ┆ ---      ┆ ---    ┆ ---                 │
│ f64      ┆ f64        ┆ f64          ┆ f64          ┆ str      ┆ str    ┆ str                 │
╞══════════╪════════════╪══════════════╪══════════════╪══════════╪════════╪═════════════════════╡
│ 0.0      ┆ 240.0      ┆ 1072.441598  ┆ 693.055117   ┆ b_memory ┆ ctr    ┆ memory_ctr_BC39.csv │
│ 0.0      ┆ 1320.0     ┆ 1093.351399  ┆ 676.847641   ┆ b_memory ┆ ctr    ┆ memory_ctr_BC39.csv │
│ 0.0      ┆ 420.0      ┆ 1104.689939  ┆ 683.918605   ┆ b_memory ┆ ctr    ┆ memory_ctr_BC39.csv │
│ 0.0      ┆ 360.0      ┆ 1093.743013  ┆ 686.18834    ┆ b_memory ┆ ctr    ┆ memory_ctr_BC39.csv │
│ 0.0      ┆ 1020.0     ┆ 1100.831004  ┆ 674.251173   ┆ b_memory ┆ ctr    ┆ memory_ctr_BC39.csv │
│ …        ┆ …          ┆ …            ┆ …            ┆ …        ┆ …      ┆ …                   │
│ 208.0    ┆ 3480.0     ┆ 962.117142   ┆ 386.679842   ┆ b_naive  ┆ mu     ┆ naive_mu_BC43.csv   │
│ 209.0    ┆ 2820.0     ┆ 544.647798   ┆ 303.863392   ┆ b_naive  ┆ mu     ┆ naive_mu_BC43.csv   │
│ 209.0    ┆ 2880.0     ┆ 544.623976   ┆ 303.76054    ┆ b_naive  ┆ mu     ┆ naive_mu_BC43.csv   │
│ 210.0    ┆ 2820.0     ┆ 962.922324   ┆ 386.545789   ┆ b_naive  ┆ mu     ┆ naive_mu_BC43.csv   │
│ 210.0    ┆ 2880.0     ┆ 962.965281   ┆ 385.993542   ┆ b_naive  ┆ mu     ┆ naive_mu_BC43.csv   │
└──────────┴────────────┴──────────────┴──────────────┴──────────┴────────┴─────────────────────┘

In [23]:
import src.object_interface as object_module
reload(object_module)
create_object = object_module.create_object

In [24]:
data_object = create_object(data)

In [25]:
spots_df = data_object.compute_spots(data, enriched=True)
print(len(spots_df['track_uid'].unique()), " unique tracks")
spots_df

8726  unique tracks

shape: (277_766, 25)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ track_id ┆ time_poin ┆ x_coordin ┆ y_coordin ┆ … ┆ cum_mean_ ┆ cum_mean_ ┆ cum_direc ┆ cum_direc │
│ ---      ┆ t         ┆ ate       ┆ ate       ┆   ┆ direction ┆ direction ┆ tion_mean ┆ tion_var  │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_change ┆ al_change ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ _ra…      ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0      ┆ 60.0      ┆ 1076.9859 ┆ 699.21816 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 77        ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 0.0      ┆ 120.0     ┆ 1074.6157 ┆ 689.56591 ┆ … ┆ null      ┆ null      ┆ -1.811598 ┆ null      │
│          ┆           ┆ 03        ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 0.0      ┆ 180.0     ┆ 1062.5455 ┆ 688.69241 ┆ … ┆ 72.063868 ┆ 0.400355  ┆ -2.440474 ┆ 0.191311  │
│          ┆           ┆ 23        ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 0.0      ┆ 240.0     ┆ 1072.4415 ┆ 693.05511 ┆ … ┆ 116.20634 ┆ 0.484193  ┆ -2.035541 ┆ 0.761379  │
│          ┆           ┆ 98        ┆ 7         ┆   ┆ 9         ┆           ┆           ┆           │
│ 0.0      ┆ 300.0     ┆ 1084.4113 ┆ 696.31536 ┆ … ┆ 80.322241 ┆ 0.267741  ┆ -0.52977  ┆ 0.813424  │
│          ┆           ┆ 02        ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 208.0    ┆ 3480.0    ┆ 962.11714 ┆ 386.67984 ┆ … ┆ null      ┆ null      ┆ -2.070479 ┆ null      │
│          ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 209.0    ┆ 2820.0    ┆ 544.64779 ┆ 303.86339 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 8         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 209.0    ┆ 2880.0    ┆ 544.62397 ┆ 303.76054 ┆ … ┆ null      ┆ null      ┆ -1.798401 ┆ null      │
│          ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 210.0    ┆ 2820.0    ┆ 962.92232 ┆ 386.54578 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 4         ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ 210.0    ┆ 2880.0    ┆ 962.96528 ┆ 385.99354 ┆ … ┆ null      ┆ null      ┆ -1.493167 ┆ null      │
│          ┆           ┆ 1         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
import src.data_compute.data_frames as frames_module
reload(frames_module)
calcs = frames_module.calc

In [27]:
calcs._enrich_spots(spots_df, t_step= 1.0)

shape: (277_766, 25)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ track_id ┆ time_poin ┆ x_coordin ┆ y_coordin ┆ … ┆ cum_mean_ ┆ cum_mean_ ┆ cum_direc ┆ cum_direc │
│ ---      ┆ t         ┆ ate       ┆ ate       ┆   ┆ direction ┆ direction ┆ tion_mean ┆ tion_var  │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ al_change ┆ al_change ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ _ra…      ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0      ┆ 60.0      ┆ 1076.9859 ┆ 699.21816 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 77        ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 0.0      ┆ 120.0     ┆ 1074.6157 ┆ 689.56591 ┆ … ┆ null      ┆ null      ┆ -1.811598 ┆ null      │
│          ┆           ┆ 03        ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 0.0      ┆ 180.0     ┆ 1062.5455 ┆ 688.69241 ┆ … ┆ 72.063868 ┆ 0.400355  ┆ -2.440474 ┆ 0.191311  │
│          ┆           ┆ 23        ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 0.0      ┆ 240.0     ┆ 1072.4415 ┆ 693.05511 ┆ … ┆ 116.20634 ┆ 0.484193  ┆ -2.035541 ┆ 0.761379  │
│          ┆           ┆ 98        ┆ 7         ┆   ┆ 9         ┆           ┆           ┆           │
│ 0.0      ┆ 300.0     ┆ 1084.4113 ┆ 696.31536 ┆ … ┆ 80.322241 ┆ 0.267741  ┆ -0.52977  ┆ 0.813424  │
│          ┆           ┆ 02        ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 208.0    ┆ 3480.0    ┆ 962.11714 ┆ 386.67984 ┆ … ┆ null      ┆ null      ┆ -2.070479 ┆ null      │
│          ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 209.0    ┆ 2820.0    ┆ 544.64779 ┆ 303.86339 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 8         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 209.0    ┆ 2880.0    ┆ 544.62397 ┆ 303.76054 ┆ … ┆ null      ┆ null      ┆ -1.798401 ┆ null      │
│          ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 210.0    ┆ 2820.0    ┆ 962.92232 ┆ 386.54578 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆           ┆ 4         ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ 210.0    ┆ 2880.0    ┆ 962.96528 ┆ 385.99354 ┆ … ┆ null      ┆ null      ┆ -1.493167 ┆ null      │
│          ┆           ┆ 1         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
tracks = data_object.compute_tracks()
tracks

shape: (8_726, 26)
┌─────────────┬────────┬──────────┬──────────┬───┬──────────┬────────────┬────────────┬────────────┐
│ group       ┆ subset ┆ set      ┆ track_id ┆ … ┆ speed_sd ┆ speed_medi ┆ directiona ┆ straightne │
│ ---         ┆ ---    ┆ ---      ┆ ---      ┆   ┆ ---      ┆ an         ┆ lity       ┆ ss         │
│ str         ┆ str    ┆ str      ┆ f64      ┆   ┆ f64      ┆ ---        ┆ ---        ┆ ---        │
│             ┆        ┆          ┆          ┆   ┆          ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪════════╪══════════╪══════════╪═══╪══════════╪════════════╪════════════╪════════════╡
│ memory_ctr_ ┆ ctr    ┆ b_memory ┆ 0.0      ┆ … ┆ 0.071081 ┆ 0.095415   ┆ 0.118236   ┆ 0.263809   │
│ BC39.csv    ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ memory_ctr_ ┆ ctr    ┆ b_memory ┆ 1.0      ┆ … ┆ 0.034672 ┆ 0.180029   ┆ 0.770144   ┆ 0.770144   │
│ BC39.csv    ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ memory_ctr_ ┆ ctr    ┆ b_memory ┆ 2.0      ┆ … ┆ 0.052644 ┆ 0.139528   ┆ 0.153487   ┆ 0.31844    │
│ BC39.csv    ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ memory_ctr_ ┆ ctr    ┆ b_memory ┆ 3.0      ┆ … ┆ 0.0467   ┆ 0.114572   ┆ 0.33939    ┆ 0.470828   │
│ BC39.csv    ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ memory_ctr_ ┆ ctr    ┆ b_memory ┆ 4.0      ┆ … ┆ 0.044352 ┆ 0.152967   ┆ 0.117396   ┆ 0.20354    │
│ BC39.csv    ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ …           ┆ …      ┆ …        ┆ …        ┆ … ┆ …        ┆ …          ┆ …          ┆ …          │
│ naive_mu_BC ┆ mu     ┆ b_naive  ┆ 206.0    ┆ … ┆ null     ┆ 0.006316   ┆ 1.0        ┆ 1.0        │
│ 43.csv      ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ naive_mu_BC ┆ mu     ┆ b_naive  ┆ 207.0    ┆ … ┆ null     ┆ 0.020625   ┆ 1.0        ┆ 1.0        │
│ 43.csv      ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ naive_mu_BC ┆ mu     ┆ b_naive  ┆ 208.0    ┆ … ┆ null     ┆ 0.007996   ┆ 1.0        ┆ 1.0        │
│ 43.csv      ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ naive_mu_BC ┆ mu     ┆ b_naive  ┆ 209.0    ┆ … ┆ null     ┆ 0.00176    ┆ 1.0        ┆ 1.0        │
│ 43.csv      ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
│ naive_mu_BC ┆ mu     ┆ b_naive  ┆ 210.0    ┆ … ┆ null     ┆ 0.009232   ┆ 1.0        ┆ 1.0        │
│ 43.csv      ┆        ┆          ┆          ┆   ┆          ┆            ┆            ┆            │
└─────────────┴────────┴──────────┴──────────┴───┴──────────┴────────────┴────────────┴────────────┘

In [29]:
# data_object.plot_tracks(fmt='html', smoothing_window=5, color='random', show_ids=True)

In [30]:
# data_object.plot_tracks(color='random', align_start=True, show_ids=True)

In [31]:
timepoints = data_object.compute_timepoints(inferative_error=True)

timepoints.to_pandas()

,set,time_point,frame,cum_track_length_min,cum_track_length_max,cum_track_length_mean,cum_track_length_median,cum_track_length_sd,cum_track_length_sem,cum_track_displacement_min,...,cum_mean_directional_change_mean,cum_mean_directional_change_median,cum_mean_directional_change_sd,cum_mean_directional_change_sem,tracks_contributing,instantaneous_direction_mean,instantaneous_direction_var,cum_direction_mean,cum_direction_var,grouping_level
0,b_memory,60.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,38,NaN,NaN,NaN,NaN,set
1,b_memory,120.0,1,0.257397,24.350969,9.824309,9.425569,6.129198,0.994287,0.257397,...,NaN,NaN,NaN,NaN,38,-1.942799,0.971972,-1.942799,0.971972,set
2,b_memory,180.0,2,1.185618,43.330047,20.018610,22.043842,10.824082,1.670192,0.738189,...,50.303777,33.570125,46.857272,7.230234,42,-1.229823,0.959951,-1.373219,0.962914,set
3,b_memory,240.0,3,0.738189,57.742287,27.671181,30.037516,15.435479,2.182906,0.738189,...,53.275431,43.001403,34.767632,4.916886,50,-0.271413,0.989031,-2.998827,0.911154,set
4,b_memory,300.0,4,0.738189,80.883361,35.746707,34.976747,19.497905,2.678243,0.610656,...,55.242722,49.739970,30.653963,4.210646,53,-1.517589,0.882852,-2.724832,0.940801,set
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3653,b_naive,3300.0,49,48.155219,689.760806,257.318467,159.037487,232.117558,69.986077,1.266587,...,78.744952,83.523324,29.259080,8.821945,11,-0.037950,0.879901,-2.659590,0.810807,set
3654,b_naive,3360.0,50,48.251735,703.817229,279.499876,163.216257,238.521006,75.426965,21.420435,...,75.440786,80.099516,27.523350,8.703647,10,-2.981684,0.637446,-2.997559,0.755298,set
3655,b_naive,3420.0,51,48.481743,718.548531,295.475500,165.798833,252.572866,84.190955,21.241997,...,72.798265,75.138590,27.695168,9.231723,9,2.688698,0.460325,-2.692411,0.721456,set
3656,b_naive,3480.0,52,48.928540,735.805251,299.711836,166.239765,256.798764,85.599588,20.796713,...,72.339364,74.129923,26.963857,8.987952,9,2.615663,0.348286,-2.791742,0.697546,set
3657,b_naive,3540.0,53,49.513723,751.111951,299.156555,164.197691,277.933779,98.264430,21.360175,...,72.826339,75.484837,29.375003,10.385632,8,-0.688080,0.595388,-2.808752,0.790708,set

In [32]:
timepoints = data_object.compute_timepoints(grouping_level='lowest')

timepoints.to_pandas()

,subset,set,time_point,frame,cum_track_length_min,cum_track_length_max,cum_track_length_mean,cum_track_length_median,cum_track_length_sd,cum_track_displacement_min,...,cum_mean_directional_change_max,cum_mean_directional_change_mean,cum_mean_directional_change_median,cum_mean_directional_change_sd,tracks_contributing,instantaneous_direction_mean,instantaneous_direction_var,cum_direction_mean,cum_direction_var,grouping_level
0,ctr,b_memory,60.0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12,NaN,NaN,NaN,NaN,subset
1,ctr,b_memory,120.0,1,4.116438,18.299556,9.871592,8.861391,4.397235,4.116438,...,NaN,NaN,NaN,NaN,12,0.470737,0.417776,0.470737,0.417776,subset
2,ctr,b_memory,180.0,2,9.307972,27.590218,19.827388,20.912197,5.085283,0.738189,...,180.000000,62.865512,46.675376,51.586075,16,-1.907164,0.958478,0.818964,0.750449,subset
3,ctr,b_memory,240.0,3,15.549812,37.702385,28.655385,31.468406,7.417218,5.867235,...,121.570095,62.060511,59.177267,35.446181,18,1.761536,0.807951,2.045203,0.883600,subset
4,ctr,b_memory,300.0,4,19.292841,56.001887,36.275170,35.477543,9.657010,7.972558,...,131.130636,62.318086,63.233896,28.933359,20,-1.427916,0.837565,2.240767,0.932723,subset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10704,mu,b_naive,3300.0,1,0.738189,7.338949,3.056903,1.093571,3.712616,0.738189,...,NaN,NaN,NaN,NaN,3,-1.420295,0.384199,-1.420295,0.384199,subset
10705,mu,b_naive,3360.0,2,1.476377,9.202197,4.120513,1.682964,4.402080,0.784413,...,136.043972,52.002254,19.962790,73.463501,3,2.553121,0.863969,-2.183177,0.620022,subset
10706,mu,b_naive,3420.0,3,1.476377,11.287471,4.980536,2.177761,5.473212,0.715513,...,74.042356,32.489747,23.426885,37.844012,3,2.001739,0.726105,3.133909,0.790886,subset
10707,mu,b_naive,3480.0,4,1.476377,13.954237,5.883049,2.218533,6.999697,0.751658,...,84.955694,36.723514,25.214849,43.631462,3,-2.750922,0.733411,-2.840222,0.678251,subset
10708,mu,b_naive,3540.0,5,1.476377,16.031167,6.675623,2.519325,8.118903,0.837026,...,78.075690,32.585664,19.681303,40.605975,3,-1.322770,0.781689,-2.512126,0.635932,subset

In [33]:
data_object

In [34]:
timelagstab = data_object.compute_timelags(grouping_level=["subset", "set"])

timelagstab.to_pandas()

Grouping set computation took 0.0000 s
Resolve uids, timeinterval and requested timelags metrics 0.0160 s
Initial data preparation took 0.0310 s
Position pair building took 0.5841 s

Clocked: '_compute_level' <- 0.4100 s


Clocked: '_compute_level' <- 0.3580 s

Level computation took 0.7680 s

Clocked: 'timelags' <- 1.4570 s

,subset,set,frame_lag,time_lag,MSD,MSD_min,MSD_max,MSD_sd,tracks_contributing,position_pairs_contributing,directional_change_mean,directional_change_var,grouping_level
0,ctr,b_memory,1,60.0,68.360899,0.0,827.611324,99.359041,1554,47641,0.027807,0.735415,subset
1,ctr,b_memory,2,120.0,209.716831,0.0,2858.016746,314.801363,1485,46087,-0.012266,0.786182,subset
2,ctr,b_memory,3,180.0,390.966461,0.0,6330.535928,614.472326,1425,44602,0.028289,0.829270,subset
3,ctr,b_memory,4,240.0,598.955210,0.0,10495.309470,979.905406,1382,43177,0.037300,0.850354,subset
4,ctr,b_memory,5,300.0,824.529007,0.0,14876.628913,1395.057081,1333,41795,-0.015437,0.895513,subset
...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,None,b_naive,55,3300.0,13146.532542,0.0,542770.084186,38780.729810,1230,5863,-1.458613,0.898725,set
468,None,b_naive,56,3360.0,13275.572111,0.0,539566.437149,39491.835134,1206,4633,0.562478,0.953873,set
469,None,b_naive,57,3420.0,13386.684399,0.0,532919.071901,40137.373064,1190,3427,2.251809,0.920204,set
470,None,b_naive,58,3480.0,13402.616402,0.0,525311.377061,40620.103590,1165,2237,-0.443798,0.828035,set
471,None,b_naive,59,3540.0,12973.380324,0.0,508858.154047,40485.925433,1072,1072,NaN,NaN,set